### ISSUE TITLE
Instagram in footer links to instagram.com instead of team Instagram page

### ISSUE THREAD

**Issue by jmelancon** [4198-Programmers/4198-webpage#6]

**Comment by LeNerd46** [comment]
The only page it links to instagram.com is the sponsors page

**Comment by jmelancon** [comment]
Is this a template issue then? It ought to be updated there too if so.

**Comment by LeNerd46** [comment]
It seems as though it is a template issue

**Comment by LeNerd46** [comment]
I fixed this a few days ago
