### ISSUE TITLE
Completely Rewrite Website

### ISSUE THREAD

**Issue by LeNerd46** [4198-Programmers/4198-webpage#8]
We did a little ctrl + c and ctrl + v. It's not that good

Please...

**Comment by snaapsh0t12** [comment]
I can start thinking of possible design ideas in about 5 days

**Comment by snaapsh0t12** [comment]
well technically every day but I would like to jot down or sketch the ideas

**Comment by LeNerd46** [comment]
We using [Sketch2Code](https://sketch2code.azurewebsites.net/)?
